In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import io, math, os, sys
from base64 import b64decode
from pathlib import Path
from IPython.core.display import HTML

import matplotlib.pyplot as plt
import numpy as np

import PIL

# Install daltonlens if necessary
try:
    from daltonlens import convert, simulate
except ImportError:
    !pip install -q daltonlens
    from daltonlens import convert, simulate
    
# Uncomment to get interactive plots.
# %matplotlib notebook

# Introduction

Goal is to generate the precomputed matrices / parameters needed by libDaltonLens or DaltonLens desktop.

# Brettel 1997 with sRGB

In [7]:
simulator = simulate.Simulator_Brettel1997(convert.LMSModel_sRGB_SmithPokorny75(), use_white_as_neutral=True)
simulator.dumpPrecomputedValues = True
np.set_printoptions(precision=4, suppress=True)

simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.PROTAN, severity=1.0)
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.DEUTAN, severity=1.0)
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.TRITAN, severity=1.0)

static float LMS_from_linearRGB[] = {
    0.17886, 0.43997, 0.03597,
    0.03380, 0.27515, 0.03621,
    0.00031, 0.00192, 0.01528
};

static float linearRGB_from_LMS[] = {
    8.00533, -12.88195, 11.68065,
    -0.97821, 5.26945, -10.18300,
    -0.04017, -0.39885, 66.48079
};

struct DLBrettel1997Params
{
    int lmsElementToProject;
    float projectionOnPlane1[3];
    float projectionOnPlane2[3];
    float separationPlaneNormal[3];
};

static struct DLBrettel1997Params brettel_protan_params = {
    0, // only this LMS coordinate is affected for protan
    { 0.00000, 2.18394, -5.65554 }, // Projection to plane 1
    { 0.00000, 2.16614, -5.30455 }, // Projection to plane 2
    { 0.00000, 0.01751, -0.34516 }  // Normal of the separation plane to pick the projection plane.
};
static float LMS_from_linearRGB[] = {
    0.17886, 0.43997, 0.03597,
    0.03380, 0.27515, 0.03621,
    0.00031, 0.00192, 0.01528
};

static float linearRGB_from_LMS[] = {
    8.00533, -12.88195, 11.68065,
    -0.978

array([[[0, 0, 0]]], dtype=uint8)

# Viénot 1999 with sRGB

In [4]:
simulator = simulate.Simulator_Vienot1999(convert.LMSModel_sRGB_SmithPokorny75())
simulator.dumpPrecomputedValues = True
np.set_printoptions(precision=4, suppress=True)

simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.PROTAN, severity=1.0)
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.DEUTAN, severity=1.0)
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.TRITAN, severity=1.0)

static float vienot_protan_rgbCvd_from_rgb[] = {
    0.10889, 0.89111, -0.00000,
    0.10889, 0.89111, 0.00000,
    0.00447, -0.00447, 1.00000
};
static float vienot_deutan_rgbCvd_from_rgb[] = {
    0.29031, 0.70969, -0.00000,
    0.29031, 0.70969, -0.00000,
    -0.02197, 0.02197, 1.00000
};
static float vienot_tritan_rgbCvd_from_rgb[] = {
    1.00000, 0.15236, -0.15236,
    0.00000, 0.86717, 0.13283,
    -0.00000, 0.86717, 0.13283
};


array([[[0, 0, 0]]], dtype=uint8)

# Brettel with Vischeck parameters

In [5]:
simulator = simulate.Simulator_Vischeck()
simulator.dumpPrecomputedValues = True
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.PROTAN, severity=1.0)
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.DEUTAN, severity=1.0)
simulator.simulate_cvd(np.zeros((1,1,3), dtype=np.uint8), simulate.Deficiency.TRITAN, severity=1.0)

static float LMS_from_linearRGB[] = {
    0.05060, 0.08585, 0.00952,
    0.01893, 0.08925, 0.01370,
    0.00292, 0.00976, 0.07146
};

static float linearRGB_from_LMS[] = {
    30.83086, -29.83266, 1.61048,
    -6.48147, 17.71558, -2.53264,
    -0.37569, -1.19907, 14.27385
};

struct DLBrettel1997Params
{
    int lmsElementToProject;
    float projectionOnPlane1[3];
    float projectionOnPlane2[3];
    float separationPlaneNormal[3];
};

static struct DLBrettel1997Params brettel_protan_params = {
    0, // only this LMS coordinate is affected for protan
    { 0.00000, 1.34585, -0.21464 }, // Projection to plane 1
    { 0.00000, 1.35426, -0.22682 }, // Projection to plane 2
    { 0.00000, 0.08414, -0.12188 }  // Normal of the separation plane to pick the projection plane.
};
static float LMS_from_linearRGB[] = {
    0.05060, 0.08585, 0.00952,
    0.01893, 0.08925, 0.01370,
    0.00292, 0.00976, 0.07146
};

static float linearRGB_from_LMS[] = {
    30.83086, -29.83266, 1.61048,
    -6.481

array([[[0, 0, 0]]], dtype=uint8)