In [1]:
%load_ext autoreload
%autoreload 2

In [3]:
import io, math, os, sys
from base64 import b64decode
from pathlib import Path
from IPython.core.display import HTML

import matplotlib.pyplot as plt
import numpy as np

import colour
from colour import MSDS_CMFS

from icecream import ic

import PIL

# Install daltonlens if necessary
try:
    from daltonlens import convert, simulate
except ImportError:
    %pip install -q daltonlens
    from daltonlens import convert, simulate

# Uncomment to get interactive plots.
# %matplotlib notebook

def normalized(p): return p / np.linalg.norm(p)

simulator = simulate.Simulator_Vienot1999(convert.LMSModel_sRGB_SmithPokorny75())
# simulator = simulate.Simulator_Brettel1997(convert.LMSModel_sRGB_SmithPokorny75())

np.set_printoptions(suppress=True, precision=5)

display(convert.LMSModel_Vischeck_GIMP().LMS_from_XYZ)
display(convert.LMSModel_sRGB_SmithPokorny75().LMS_from_XYZ)
display(convert.LMSModel_sRGB_StockmanSharpe2000().LMS_from_XYZ)
display(convert.LMSModel_Vienot1999_SmithPokorny75().LMS_from_XYZ)

print()
ic(convert.LMSModel_Vischeck_GIMP().LMS_from_linearRGB)
ic(convert.LMSModel_sRGB_SmithPokorny75().LMS_from_linearRGB)
ic(convert.LMSModel_sRGB_StockmanSharpe2000().LMS_from_linearRGB)
ic(convert.LMSModel_Vienot1999_SmithPokorny75().LMS_from_linearRGB)

array([[ 0.08128,  0.08134, -0.01159],
       [-0.0244 ,  0.13555,  0.00876],
       [ 0.00399, -0.00077,  0.0745 ]])

array([[ 0.15514,  0.54312, -0.03286],
       [-0.15514,  0.45684,  0.03286],
       [ 0.     ,  0.     ,  0.01608]])

array([[ 1.94735, -1.41445,  0.36476],
       [ 0.6899 ,  0.34832,  0.     ],
       [ 0.     ,  0.     ,  1.93485]])

array([[ 0.15514,  0.54312, -0.03286],
       [-0.15514,  0.45684,  0.03286],
       [ 0.     ,  0.     ,  0.01608]])

ic| convert.LMSModel_Vischeck_GIMP().LMS_from_linearRGB: array([[ 0.0506 ,  0.08585,  0.00952],
                                                                [ 0.01893,  0.08925,  0.0137 ],
                                                                [ 0.00292,  0.00976,  0.07146]])
ic| convert.LMSModel_sRGB_SmithPokorny75().LMS_from_linearRGB: array([[ 0.17886,  0.43997,  0.03597],
                                                                      [ 0.0338 ,  0.27515,  0.03621],
                                                                      [ 0.00031,  0.00192,  0.01528]])
ic| convert.LMSModel_sRGB_StockmanSharpe2000().LMS_from_linearRGB: array([[ 0.50944, -0.27174,  0.59592],
                                                                          [ 0.35863,  0.4958 ,  0.14962],
                                                                          [ 0.03741,  0.23062,  1.8387 ]])
ic| convert.LMSModel_Vienot1999_SmithPokorny75().LMS_from_linearRGB: array([[ 0.07013

array([[ 0.07013,  0.17065,  0.01615],
       [ 0.01355,  0.10649,  0.01517],
       [ 0.00012,  0.00072,  0.00575]])

In [4]:
gimp_lms_475 = np.array([0.08008, 0.1579, 0.5897])
gimp_lms_575 = np.array([0.9856, 0.7325, 0.001079])
gimp_lms_485 = np.array([0.1284, 0.2237, 0.3636])
gimp_lms_660 = np.array([0.0914, 0.007009, 0.0])

vischeck = convert.LMSModel_Vischeck_GIMP()
for lms in [gimp_lms_475, gimp_lms_575, gimp_lms_485, gimp_lms_660]:
    ic(vischeck.XYZ_from_LMS @ lms)

ic| vischeck.XYZ_from_LMS @ lms: array([ 1.22694,  0.87814,  7.85903])
ic| vischeck.XYZ_from_LMS @ lms: array([ 5.65322,  6.43625, -0.2219 ])
ic| vischeck.XYZ_from_LMS @ lms: array([ 0.79132,  1.4793 ,  4.85354])
ic| vischeck.XYZ_from_LMS @ lms: array([ 0.90089,  0.21688, -0.04599])


In [ ]:
anchor_e_gimp = np.array([0.05059983 + 0.08585369 + 0.00952420, 
                     0.01893033 + 0.08925308 + 0.01370054,
                     0.00292202 + 0.00975732 + 0.07145979])
ic(anchor_e_gimp)

In [ ]:
cmfs = MSDS_CMFS['CIE 1931 2 Degree Standard Observer']
xyz_475 = colour.wavelength_to_XYZ(475, cmfs)
xyz_575 = colour.wavelength_to_XYZ(575, cmfs)
xyz_485 = colour.wavelength_to_XYZ(485, cmfs)
xyz_660 = colour.wavelength_to_XYZ(660, cmfs)
ic(normalized(xyz_475))
ic(normalized(xyz_575))

d65_white_xyz = np.array([95.05, 100.00, 108.88])
white_xyz = np.array([100.0, 100.00, 100.0])
xyz_475_d65 = colour.chromatic_adaptation(xyz_475, d65_white_xyz, white_xyz)
xyz_575_d65 = colour.chromatic_adaptation(xyz_575, d65_white_xyz, white_xyz)
ic(normalized(xyz_475_d65))
ic(normalized(xyz_575_d65))

In [ ]:
cmfs = MSDS_CMFS['Stockman & Sharpe 2 Degree Cone Fundamentals']
xyz_475 = colour.wavelength_to_XYZ(475, cmfs)
xyz_575 = colour.wavelength_to_XYZ(575, cmfs)
xyz_485 = colour.wavelength_to_XYZ(485, cmfs)
xyz_660 = colour.wavelength_to_XYZ(660, cmfs)
ic(normalized(xyz_475))
ic(normalized(xyz_575))